/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Shell_OPEN_Server_H
#define Shell_OPEN_Server_H

#include <thrift/TDispatchProcessor.h>
#include "test_types.h"

namespace open {

class Shell_OPEN_ServerIf {
 public:
  virtual ~Shell_OPEN_ServerIf() {}
  virtual void shell(const std::string& query) = 0;
};

class Shell_OPEN_ServerIfFactory {
 public:
  typedef Shell_OPEN_ServerIf Handler;

  virtual ~Shell_OPEN_ServerIfFactory() {}

  virtual Shell_OPEN_ServerIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(Shell_OPEN_ServerIf* /* handler */) = 0;
};

class Shell_OPEN_ServerIfSingletonFactory : virtual public Shell_OPEN_ServerIfFactory {
 public:
  Shell_OPEN_ServerIfSingletonFactory(const boost::shared_ptr<Shell_OPEN_ServerIf>& iface) : iface_(iface) {}
  virtual ~Shell_OPEN_ServerIfSingletonFactory() {}

  virtual Shell_OPEN_ServerIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(Shell_OPEN_ServerIf* /* handler */) {}

 protected:
  boost::shared_ptr<Shell_OPEN_ServerIf> iface_;
};

class Shell_OPEN_ServerNull : virtual public Shell_OPEN_ServerIf {
 public:
  virtual ~Shell_OPEN_ServerNull() {}
  void shell(const std::string& /* query */) {
    return;
  }
};

typedef struct _Shell_OPEN_Server_shell_args__isset {
  _Shell_OPEN_Server_shell_args__isset() : query(false) {}
  bool query;
} _Shell_OPEN_Server_shell_args__isset;

class Shell_OPEN_Server_shell_args {
 public:

  Shell_OPEN_Server_shell_args() : query() {
  }

  virtual ~Shell_OPEN_Server_shell_args() throw() {}

  std::string query;

  _Shell_OPEN_Server_shell_args__isset __isset;

  void __set_query(const std::string& val) {
    query = val;
  }

  bool operator == (const Shell_OPEN_Server_shell_args & rhs) const
  {
    if (!(query == rhs.query))
      return false;
    return true;
  }
  bool operator != (const Shell_OPEN_Server_shell_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Shell_OPEN_Server_shell_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Shell_OPEN_Server_shell_pargs {
 public:


  virtual ~Shell_OPEN_Server_shell_pargs() throw() {}

  const std::string* query;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Shell_OPEN_Server_shell_result {
 public:

  Shell_OPEN_Server_shell_result() {
  }

  virtual ~Shell_OPEN_Server_shell_result() throw() {}


  bool operator == (const Shell_OPEN_Server_shell_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Shell_OPEN_Server_shell_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Shell_OPEN_Server_shell_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Shell_OPEN_Server_shell_presult {
 public:


  virtual ~Shell_OPEN_Server_shell_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class Shell_OPEN_ServerClient : virtual public Shell_OPEN_ServerIf {
 public:
  Shell_OPEN_ServerClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  Shell_OPEN_ServerClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void shell(const std::string& query);
  void send_shell(const std::string& query);
  void recv_shell();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class Shell_OPEN_ServerProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<Shell_OPEN_ServerIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (Shell_OPEN_ServerProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_shell(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  Shell_OPEN_ServerProcessor(boost::shared_ptr<Shell_OPEN_ServerIf> iface) :
    iface_(iface) {
    processMap_["shell"] = &Shell_OPEN_ServerProcessor::process_shell;
  }

  virtual ~Shell_OPEN_ServerProcessor() {}
};

class Shell_OPEN_ServerProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  Shell_OPEN_ServerProcessorFactory(const ::boost::shared_ptr< Shell_OPEN_ServerIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< Shell_OPEN_ServerIfFactory > handlerFactory_;
};

class Shell_OPEN_ServerMultiface : virtual public Shell_OPEN_ServerIf {
 public:
  Shell_OPEN_ServerMultiface(std::vector<boost::shared_ptr<Shell_OPEN_ServerIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~Shell_OPEN_ServerMultiface() {}
 protected:
  std::vector<boost::shared_ptr<Shell_OPEN_ServerIf> > ifaces_;
  Shell_OPEN_ServerMultiface() {}
  void add(boost::shared_ptr<Shell_OPEN_ServerIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void shell(const std::string& query) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->shell(query);
    }
    ifaces_[i]->shell(query);
  }

};

} // namespace

#endif
