/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Shell_CONSTANTS_H
#define Shell_CONSTANTS_H

#include "Shell_types.h"

namespace open {

class ShellConstants {
 public:
  ShellConstants();

};

extern const ShellConstants g_Shell_constants;

} // namespace

#endif
