/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Thrift_SERVER_H
#define Thrift_SERVER_H

#include "Shell.h"

namespace open{
	void startHttpServer(int port);

	void startWebsocketServer(int port);

	void log(char*);

	class ShellHandler : virtual public ShellIf {
	public:

		void shell(const std::string& query);
	};
}

#endif
