/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Shell_constants.h"

namespace open {

const ShellConstants g_Shell_constants;

ShellConstants::ShellConstants() {
}

} // namespace

