// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Shell.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/protocol/TJSONProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>
#include <thrift/transport/THttpServer.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::open;

class ShellHandler : virtual public ShellIf {
public:
	ShellHandler() {
		// Your initialization goes here
	}

	void shell(const std::string& query) {
		// Your implementation goes here
		printf("shell: %s\n", query.c_str());
	}

};

int main(int argc, char **argv) {
	TWinsockSingleton::create();
	int port = 9090;
	shared_ptr<ShellHandler> handler(new ShellHandler());
	shared_ptr<TProcessor> processor(new ShellProcessor(handler));
	shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
	shared_ptr<TTransportFactory> transportFactory(new THttpServerTransportFactory());
	shared_ptr<TProtocolFactory> protocolFactory(new TJSONProtocolFactory());

	TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
	server.serve();
	return 0;
}

